### ISSUE TITLE
Game settings

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2023_Pipaluk#3]
As I see in the code, the game resolution and FPS are fixed but I don't see the reason for the limitation. I ran the game in fullscreen and "artificially" removed the FPS cap and it performed fine on a GTX 1060 6GB and I have to say it still looks amazing :) 

If the codebase allows it, I would consider adding a "toggle" button between 30/60 FPS and a choice of a few resolution values (both 4:3 and 16:9 if possible).

**Comment by daniilgrbic** [comment]
Since the game isn't by any means computationally heavy, removing the FPS limit would serve no purpose other than increase resource consumption. Additionally, some aspects of the game, most notably animations, depend on the frame rate; thus, changing this would introduce no benefits while creating issues.

The resolution of the game is not fixed. Pipaluk supports any resolution and layout - to a reasonable extent - it runs and looks fine all the way from 256x160 to 4k.

![Screenshot from 2023-05-03 15-35-04](https://user-images.githubusercontent.com/43475005/235950530-b53b130d-8f44-4328-a088-96f69f40fa25.png)
![Screenshot from 2023-05-03 15-35-16](https://user-images.githubusercontent.com/43475005/235950543-09a31c96-d66f-4a70-b3ea-2406976f49d6.png)
![Screenshot from 2023-05-03 15-52-09](https://user-images.githubusercontent.com/43475005/235950548-a930f037-9de8-4d9e-8d2e-6015746b7cfc.png)

**Comment by ivan-ristovic** [comment]
For the FPS, I didn't suggest to remove the cap. I understand you wish to keep the retro aspect of the game and I totally agree. What is the current FPS value? Old NES consoles ran at ~60, I think you should definitely try to play it at 60 and see how it feels (assuming you haven't done that already and willingly decided on this FPS value). That is why I suggested a toggle option, if it is not breaking the code too much. I do not see how animations are the problem, the sleep value for the next animation frame can be calculated based on the FPS value? Am I missing something there?

The game window is responsive, yes, and will fit into any layout, and that is all fine and how it should be. But that is not the same as ingame resolution, which is always fixed at 1200x800 (if I remember well), and scales to the window size. How hard would it be to softcode the resolution setting, or calculate it dynamically based on the window size (I am not suggesting to do this, just wondering if you thought about it)?
